### ISSUE TITLE
Update to SF Symbols 6.0

### ISSUE THREAD

**Issue by NikSavchenk0** [marcbouchenoire/symbolist#103]
More than 800 new symbols including devices, car indicators, health and fitness symbols, formatting elements and more.
https://developer.apple.com/sf-symbols/

**Comment by marcbouchenoire** [comment]
`main` is now on SF Symbols 5.1 and I published [a beta release for 6.0](https://www.npmjs.com/package/symbolist/v/6.0.0-beta1) since it's not out yet.
